name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure --enable-static --disable-optimizations --disable-mmx --disable-stripping --enable-debug=3 --enable-pthreads
    - name: make
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: result-artifact
        path: bin/ffmpeg
