name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get -y install autoconf automake build-essential cmake git-core libass-dev libfreetype6-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev meson ninja-build pkg-config texinfo wget yasm zlib1g-dev openssl libssl-dev
    - name: configure
      run: ./configure --enable-static --disable-optimizations --disable-mmx --disable-stripping --enable-debug=3 --enable-pthreads --enable-openssl
    - name: make
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: result-artifact
        path: ffmpeg
